name: Release Scheduler
on:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  releaseScheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-scheduler
        uses: koj-co/release-scheduler@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
